runtime: python37
env: standard
service: app-flask
env_variables:
  # production/development
  FLASK_ENV: production
  # 1:TRUE/0:FALSE
  FLASK_DEBUG: 0
  FLASK_APP: main.py
  FLASK_RUN_PORT: 8080
  APP_NAME: app-flask
  LOG_NAME: app-flask
entrypoint: gunicorn -b :$FLASK_RUN_PORT main:app
